# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sure Stride
logo: ../assets/logo/logo.png
bookmark: ../assets/logo/bookmark.png
email: dean@surestride.net
description1: "Optimize teamwork with Agile coaching.<br />
Elevate collaboration, efficiency, and innovation.<br />
Explore our services"
description2: "Empower your team through Agile coaching. <br />
Enhance communication, adaptability, and delivery excellence.<br />
Discover how our services can drive results and unlock your team's full potential"
description3: "Streamline workflows, reduce bottlenecks.<br />
Cultivate a culture of rapid adaptation.<br />
See how our services can revolutionize your team's approach to project management"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Sure Stride
address_line: Saxony-Anhalt, Germany
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d145020.74077077053!2d11.943483395958914!3d51.31547400100605!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47a685b3a07b7fc1%3A0xf59c30c1f0e3f960!2sGeiseltalsee!5e0!3m2!1sen!2ssg!4v1699332039728!5m2!1sen!2ssg

# Social Link
facebook_link: http://www.facebook.com
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
